import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MarkGithubIcon } from '@primer/octicons-react'
import "./globals.css";
import styles from "@/app/layout.module.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.container}>
          <header className={styles.header}>
            <Link href="/">Quiz App!</Link>
            <nav>
              <Link href="/info">Info</Link>
            </nav>
          </header>
          <main className={styles.main}>
            <div className={styles.page}>
              {children}
            </div>
          </main>
          <footer className={styles.footer}>
            <span>
              Made by Thang<br/>09/06/2025
            </span>
            <a href="https://github.com/ducthang-vu/quiz-app"><MarkGithubIcon size={16}/></a>
          </footer>
        </div>
      </body>
    </html>
  );
}
